version: 3
services:
  keycloak:
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: 02091945@Rr++
      KEYCLOAK_LOGLEVEL: ALL
      KEYCLOAK_FRONTEND_URL: https://security-authnz.sobreiro.dev/auth
      DB_VENDOR: postgres
      DB_ADDR: dbpostgresqleastus2meddistauthzn.postgres.database.azure.com
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: dbpostgresqleastus2meddistauthzn
      DB_PASSWORD: 02091945@Rr++
    restart: always